using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DMS_Connector.Business_Logic.DataContract.Configuracion.Configuracion_Sucursal
{
    public class Configuracion_Sucursal
    {
        public Int32 DocEntry { get; set; }
        public Int32? DocNum { get; set; }
        public Int32? Period { get; set; }
        public Int32? Instance { get; set; }
        public Int32? Series { get; set; }
        public String Handwrtten { get; set; }
        public String Canceled { get; set; }
        public Int32? LogInst { get; set; }
        public Int32? UserSign { get; set; }
        public String Transfered { get; set; }
        public String Status { get; set; }
        public String DataSource { get; set; }
        public String U_Sucurs { get; set; }
        public String U_SerOfC { get; set; }
        public String U_SerOrC { get; set; }
        public String U_SerOfV { get; set; }
        public String U_SerOrV { get; set; }
        public String U_SerInv { get; set; }
        public String U_ArtCita { get; set; }
        public String U_DesSOfC { get; set; }
        public String U_DesSOfV { get; set; }
        public String U_DesSOrV { get; set; }
        public String U_DesSOrC { get; set; }
        public String U_DesSInv { get; set; }
        public DateTime ? U_HoraInicio { get; set; }
        public DateTime? U_HoraFin { get; set; }
        public DateTime? U_HoraIS { get; set; }
        public DateTime? U_HoraFS { get; set; }
        public DateTime? U_HoraID { get; set; }
        public DateTime? U_HoraFD { get; set; }
        public String U_CodCitaCancel { get; set; }
        public String U_CodCitaNueva { get; set; }
        public String U_CodCitaTarde { get; set; }
        public String U_CodCitaAnula { get; set; }
        public String U_CantMinTarde { get; set; }
        public String U_CantHorasValida { get; set; }
        public String U_UsaDurEC { get; set; }
        public String U_Imp_Serv { get; set; }
        public String U_Imp_Repuestos { get; set; }
        public String U_Imp_Suminis { get; set; }
        public String U_Imp_ServExt { get; set; }
        public String U_CosteoMO_C { get; set; }
        public String U_CosteoMO_I { get; set; }
        public String U_TiempoEst_C { get; set; }
        public String U_TiempoReal_C { get; set; }
        public String U_Moneda_C { get; set; }
        public String U_CuentaSys_C { get; set; }
        public String U_DescCuenta_C { get; set; }
        public String U_CtaAcreGast { get; set; }
        public String U_CtaDebGast { get; set; }
        public String U_MonDocGastos { get; set; }
        public String U_GenASGastos { get; set; }
        public String U_GenFAGastos { get; set; }
        public String U_DescCtaAcreGast { get; set; }
        public String U_DescCtaDebGast { get; set; }
        public String U_Imp_Gastos { get; set; }
        public String U_USolOTEsp { get; set; }
        public String U_ValKm { get; set; }
        public String U_SDocCot { get; set; }
        public String U_ValHS { get; set; }
        public String U_Entrega_Rep { get; set; }
        public String U_ValReqPen { get; set; }
        public String U_TiempoOFV_C { get; set; }
        public String U_Requis { get; set; }
        public String U_UseParts { get; set; }
        public String U_UseServ { get; set; }
        public String U_UseSE { get; set; }
        public String U_UseSum { get; set; }
        public String U_AsigTecOT { get; set; }
        public String U_ValTiemEst { get; set; }
        public String U_FinOTCanSol { get; set; }
        public String U_CambPreTall { get; set; }
        public String U_AsigUniMec { get; set; }
        public String U_UseLisPreCli { get; set; }
        public String U_GenOTEsp { get; set; }
        public String U_ValOTCreEsp { get; set; }
        public Double? U_CopiasOT { get; set; }
        public String U_UnidadTiemp { get; set; }
        public String U_UseCliFilter { get; set; }
        public String U_CitCliInac { get; set; }
        public String U_UsaOrdVenta { get; set; }
        public String U_UsaOfeVenta { get; set; }
        public String U_ListaPrecios { get; set; }
        public String U_CodLisPre { get; set; }
        public Double? U_UniTpMint { get; set; }
        public String U_NoBodRep { get; set; }
        public String U_NoBodPro { get; set; }
        public String U_NoBodSE { get; set; }
        public String U_NoBodSum { get; set; }
        public String U_AsigAutCol { get; set; }
        public String U_SEInvent { get; set; }
        public String U_CostoSimp { get; set; }
        public String U_CostoDet { get; set; }
        public String U_MsjXCC { get; set; }
        public DateTime? U_HorAlI { get; set; }
        public DateTime? U_HoraAlF { get; set; }
        public String U_GrpTrabajo { get; set; }
        public String U_FOTAPen { get; set; }
        public String U_HjaCanPen { get; set; }
        public String U_PerCanOT { get; set; }
        public String U_CanOTSer { get; set; }
        public String U_CanOTArAp { get; set; }
        public String U_Imp_RepVenta { get; set; }
        public String U_SolaUna { get; set; }
        public String U_Dir_Img_Ot { get; set; }
        public String U_CitaSinAsesor { get; set; }
        public String U_UsaSolEsp { get; set; }
        public String U_CtaDebitoMO { get; set; }
        public String U_DesCtaDebitoMO { get; set; }
        public String U_CtaDebitoCosto { get; set; }
        public String U_DesCtaDebitoCosto { get; set; }
        public String U_CtaDotacionSE { get; set; }
        public String U_DesCtaDotacionSE { get; set; }
        public String U_CtaGastosSE { get; set; }
        public String U_DesCtaGastosSE { get; set; }
        public String U_CtaDifPrecioSE { get; set; }
        public String U_DesCtaDifPrecioSE { get; set; }
        public String U_CtaCostosBVSE { get; set; }
        public String U_DesCtaCostosBVSE { get; set; }
        public String U_UsaPreAutSE { get; set; }
        public String U_ImpRepCom { get; set; }
        public String U_ImpSECom { get; set; }
        public String U_FinalizaAct2Click { get; set; }
        public String U_AgrgTiempFin { get; set; }
        public String U_AddMecNEstado { get; set; }
        public String U_DesAproSE { get; set; }
        public String U_DesAproSER { get; set; }
        public String U_AgendaColor { get; set; }
        public String U_PCanOTAct { get; set; }
        public String U_DirectTransfer { get; set; }
        public List<Aprobaciones_Sucursal> Aprobaciones_Sucursal { get; set; }
        public List<Bodegas_CentroCosto> Bodegas_CentroCosto { get; set; }
        public List<Configuracion_OT_Interna> Configuracion_OT_Interna { get; set; }
        public List<Configuracion_Tipo_Orden> Configuracion_Tipo_Orden { get; set; }
        public String U_GenReqCOV { get; set; }
        public String U_CloseSOL { get; set; }
        public String U_UsaLAOV { get; set; }
        public String U_ManageColorBy { get; set; }
        public String U_UsePrepicking { get; set; }
        public String U_MTechnician { get; set; }
        public String U_PrepickingSS { get; set; }
        public String U_PrepickingCS { get; set; }
        public String U_UsaEstadosOTP { get; set; }
        public Double U_ExtraHourRate { get; set; }
        public String U_CalHT { get; set; }
        public String U_DraftD { get; set; }
        public Dictionary<DayOfWeek, Horario> HorarioSucursal { get; set; }
    }
}
