using System;
using System.Collections.Generic;

namespace DMS_Connector.Business_Logic.DataContract.Configuracion.Parametrizaciones_Generales
{
    public class Admin
    {
        public String Code { get; set; }
        public String Name { get; set; }
        public Int32 DocEntry { get; set; }
        public String Canceled { get; set; }
        public Int32? LogInst { get; set; }
        public Int32? UserSign { get; set; }
        public String Transfered { get; set; }
        public String DataSource { get; set; }
        public Int32? U_Etap_CRM { get; set; }
        public String U_Disp_V { get; set; }
        public String U_Disp_R { get; set; }
        public String U_Inven_V { get; set; }
        public String U_Inven_R { get; set; }
        public String U_Placa_Pr { get; set; }
        public String U_Serie_U { get; set; }
        public String U_CFL_Vehi { get; set; }
        public String U_Reportes { get; set; }
        public Int32? U_Tipo_DD { get; set; }
        public Double? U_Monto_GL { get; set; }
        public String U_OTROS_AC { get; set; }
        public String U_TRAN_AA { get; set; }
        public Int32? U_SCGD_EtapaCV { get; set; }
        public String U_SCGD_ModPrecio { get; set; }
        public String U_SCGD_AccInv { get; set; }
        public String U_SCGD_BodAcc { get; set; }
        public String U_GeSalAut { get; set; }
        public String U_NCSalNeg { get; set; }
        public String U_SCGD_VIN { get; set; }
        public String U_SCGD_Uni { get; set; }
        public String U_Perm_Fac { get; set; }
        public String U_Disp_Res { get; set; }
        public String U_Usa_Fin { get; set; }
        public String U_Usa_Plc { get; set; }
        public String U_Periodo { get; set; }
        public String U_Niv_Fin { get; set; }
        public String U_Niv_Usa { get; set; }
        public String U_NivAprob { get; set; }
        public String U_Desc_Fac { get; set; }
        public String U_Mul_Fac { get; set; }
        public String U_AxEst { get; set; }
        public String U_Mon_Def { get; set; }
        public String U_Usa_FiEx { get; set; }
        public String U_AlmGeTra { get; set; }
        public String U_CostSExFP { get; set; }
        public String U_Pag_Prim { get; set; }
        public String U_UsaLed { get; set; }
        public String U_EspVehic { get; set; }
        public String U_UsaAXEV { get; set; }
        public String U_SCGD_Pla { get; set; }
        public String U_TiemEsta { get; set; }
        public String U_AdcApr { get; set; }
        public String U_RepPre { get; set; }
        public String U_CTCosAcc { get; set; }
        public String U_UsaAxC { get; set; }
        public String U_ModCDes { get; set; }
        public String U_CnpDMS { get; set; }
        public String U_ValTipoInv { get; set; }
        public String U_TransCostCero { get; set; }
        public String U_FechaRes { get; set; }
        public String U_BO_Parc { get; set; }
        public String U_TCCont { get; set; }
        public String U_Ramv { get; set; }
        public String U_Pagos_Rec { get; set; }
        public String U_MoPreVta { get; set; }
        public String U_CtaFiDe { get; set; }
        public String U_CtaFiHa { get; set; }
        public String U_CtaAsDe { get; set; }
        public String U_CtaAsHa { get; set; }
        public String U_AlGenOC { get; set; }
        public String U_UtCos { get; set; }
        public String U_UsaDimC { get; set; }
        public String U_UsaComi { get; set; }
        public String U_CosteoLocal { get; set; }
        public String U_ReduceCant { get; set; }
        public String U_Gen_Draft_Cost { get; set; }
        public String U_ValongVIN { get; set; }
        public String U_SCGD_AnoUs { get; set; }
        public String U_OT_SAP { get; set; }
        public String U_ConCUCV { get; set; }
        public String U_ValCompAE { get; set; }
        public String U_NewDMUCV { get; set; }
        public String U_UsaConfI { get; set; }
        public String U_UsaWHTramites { get; set; }
        public String U_ValLeaSN { get; set; }
        public String U_CodLeaSN { get; set; }
        public String U_UsaTrmFac { get; set; }
        public String U_GenAsSE { get; set; }
        public String U_UsaCostAuto { get; set; }
        public String U_UsaFactPorUnid { get; set; }
        public String U_UsaFExVU { get; set; }
        public String U_UsaDSNRU { get; set; }
        public String U_SeTra { get; set; }
        public String U_UsaFPVU { get; set; }
        public String U_TipoTransCostAuto { get; set; }
        public String U_Usa_IFord { get; set; }
        public String U_UsaUbicD { get; set; }
        public String U_UsaFilRep { get; set; }
        public String U_UsaFilSer { get; set; }
        public String U_Devol_Veh { get; set; }
        public String U_UsaTAva { get; set; }
        public String U_Busq_exac { get; set; }
        public String U_UsaSegPV { get; set; }
        public String U_ValReVen { get; set; }
        public String U_SCGD_CSLoc { get; set; }
        public String U_EditKmCV { get; set; }
        public String U_UsaVATGroup { get; set; }
        public String U_LocCR { get; set; }
        public String U_CodLisPre { get; set; }
        public String U_CtrlAcc { get; set; }
        public String U_UsaBanCl { get; set; }
        public String U_GenAsSeg { get; set; }
        public String U_GenFacCns { get; set; }
        public String U_UsaPrecioSalida { get; set; }
        public String U_BloqEntradaSA { get; set; }
        public String U_FieldsPosition { get; set; }
        public String U_SchSizeMode { get; set; }
        public String U_ScheduleType { get; set; }
        public String U_VerCostoS { get; set; }
        public String U_CABYS_CR { get; set; }
        public List<Admin1> Admin1 { get; set; }
        public List<Admin2> Admin2 { get; set; }
        public List<Admin3> Admin3 { get; set; }
        public List<Admin4> Admin4 { get; set; }
        public List<Admin5> Admin5 { get; set; }
        public List<Admin6> Admin6 { get; set; }
        public List<Admin7> Admin7 { get; set; }
        public List<Admin8> Admin8 { get; set; }
        public List<Admin9> Admin9 { get; set; }
    }
}
