using System;
using System.Collections.Generic;

namespace DMS_Connector.Business_Logic.DataContract.Contrato_de_Ventas
{
    public class CVenta
    {
        public Int32 DocEntry { get; set; }
        public Int32? DocNum { get; set; }
        public Int32? Period { get; set; }
        public Int32? Instance { get; set; }
        public Int32? Series { get; set; }
        public String Handwrtten { get; set; }
        public String Canceled { get; set; }
        public String Object { get; set; }
        public Int32? LogInst { get; set; }
        public Int32? UserSign { get; set; }
        public String Transfered { get; set; }
        public String Status { get; set; }
        public String DataSource { get; set; }
        public String U_CardCode { get; set; }
        public String U_CardName { get; set; }
        public Int32? U_Tipo { get; set; }
        public Int32? U_Estado { get; set; }
        public String U_Opcion { get; set; }
        public Double? U_Pre_Vta { get; set; }
        public Double? U_Ext_Adi { get; set; }
        public Double? U_Gas_Ins { get; set; }
        public Double? U_Gas_Seg { get; set; }
        public Double? U_Gas_Pre { get; set; }
        public Double? U_DocTotal { get; set; }
        public Double? U_Saldo { get; set; }
        public String U_Observ { get; set; }
        public String U_Dat_Pre { get; set; }
        public Int32? U_SlpCode { get; set; }
        public String U_SlpName { get; set; }
        public DateTime? U_DocDate { get; set; }
        public DateTime? U_Fec_Ent { get; set; }
        public String U_Cod_Unid { get; set; }
        public String U_Cod_Marc { get; set; }
        public String U_Des_Marc { get; set; }
        public String U_Cod_Mode { get; set; }
        public String U_Des_Mode { get; set; }
        public String U_Cod_Esti { get; set; }
        public String U_Des_Esti { get; set; }
        public Int32? U_Ano_Vehi { get; set; }
        public String U_Num_Plac { get; set; }
        public String U_Cod_Col { get; set; }
        public String U_Des_Col { get; set; }
        public String U_Num_VIN { get; set; }
        public String U_Num_Mot { get; set; }
        public Double? U_Mar_Brt { get; set; }
        public Double? U_Mon_Fin { get; set; }
        public String U_Ent_Fin { get; set; }
        public Double? U_Mon_pre { get; set; }
        public Int32? U_Plazo { get; set; }
        public Double? U_Tas_Anu { get; set; }
        public Double? U_Abo_Men { get; set; }
        public Double? U_Cuo_Tot { get; set; }
        public Double? U_Seg_Pre { get; set; }
        public String U_Obs_Pre { get; set; }
        public String U_Unid_Us { get; set; }
        public String U_Marc_Us { get; set; }
        public String U_Esti_us { get; set; }
        public String U_Mot_Us { get; set; }
        public String U_VIN_Us { get; set; }
        public Int16? U_Anio_Us { get; set; }
        public String U_Plac_Us { get; set; }
        public String U_Col_Us { get; set; }
        public String U_Obs_Us { get; set; }
        public String U_IDVehi { get; set; }
        public Double? U_Deposito { get; set; }
        public Double? U_Mon_Usa { get; set; }
        public Double? U_Deu_Usa { get; set; }
        public Double? U_Nota_Cre { get; set; }
        public Double? U_Pag_ent { get; set; }
        public DateTime? U_Aval_us { get; set; }
        public Int32? U_RTV_MM { get; set; }
        public Int32? U_RTV_AAAA { get; set; }
        public Int32? U_Gravamen { get; set; }
        public Double? U_Val_Rec { get; set; }
        public Double? U_Val_Inv { get; set; }
        public String U_Usu_Tra { get; set; }
        public String U_Usu_Ven { get; set; }
        public String U_Usu_Gen { get; set; }
        public String U_Usu_Fac { get; set; }
        public String U_Usu_Can { get; set; }
        public DateTime? U_Fec_Tra { get; set; }
        public DateTime? U_Fec_Ven { get; set; }
        public DateTime? U_Fec_Gen { get; set; }
        public DateTime? U_Fec_Fac { get; set; }
        public DateTime? U_Fec_Can { get; set; }
        public String U_Det_Ext { get; set; }
        public DateTime? U_Gra_Fec { get; set; }
        public Double? U_Financia { get; set; }
        public Double? U_Gas_Loc { get; set; }
        public Double? U_Cos_Acc { get; set; }
        public String U_No_Fac { get; set; }
        public String U_Obs_GV { get; set; }
        public String U_Obs_GG { get; set; }
        public String U_Moneda { get; set; }
        public String U_Ent_FiP { get; set; }
        public String U_Tip_Tasa { get; set; }
        public DateTime? U_Der_Cir { get; set; }
        public String U_Cat_Us { get; set; }
        public String U_Tip_Us { get; set; }
        public String U_Trac_Us { get; set; }
        public String U_Cab_Us { get; set; }
        public String U_Prop_Us { get; set; }
        public String U_CEnt_Fi { get; set; }
        public String U_CEnt_FP { get; set; }
        public String U_CCl_Veh { get; set; }
        public String U_NCl_Veh { get; set; }
        public DateTime? U_Fec_1Ab { get; set; }
        public Int32? U_GroupNum { get; set; }
        public String U_Cod_FP { get; set; }
        public Double? U_Nota_Deb { get; set; }
        public String U_Cod_NotD { get; set; }
        public String U_Nam_Acre { get; set; }
        public String U_Cod_Nota { get; set; }
        public String U_Cod_N_Us { get; set; }
        public String U_ID_VehUs { get; set; }
        public String U_Reaproba { get; set; }
        public String U_Cod_Acre { get; set; }
        public String U_OwrCode { get; set; }
        public String U_OwrName { get; set; }
        public String U_Transmis { get; set; }
        public String U_Cod_A_DU { get; set; }
        public String U_Cod_A_Co { get; set; }
        public String U_Cod_OV { get; set; }
        public String U_Name_OV { get; set; }
        public Double? U_Otros_C { get; set; }
        public Double? U_Otros_L { get; set; }
        public Double? U_Pagos { get; set; }
        public Double? U_PrecioVeh { get; set; }
        public String U_Foo { get; set; }
        public String U_SCGD_CodCotiz { get; set; }
        public String U_SCGD_NameCotiz { get; set; }
        public Double? U_SCGD_TipoCambio { get; set; }
        public String U_SCGD_NoSalida { get; set; }
        public String U_SCGD_DocPreliminar { get; set; }
        public String U_Reversa { get; set; }
        public Double? U_Mon_Cot { get; set; }
        public Double? U_Pre_Us { get; set; }
        public String U_Gravo { get; set; }
        public String U_FooVend { get; set; }
        public Double? U_Pre_Imp { get; set; }
        public DateTime? U_SCGD_FDc { get; set; }
        public Double? U_Pre_Vh { get; set; }
        public Double? U_Pago_Vh { get; set; }
        public String U_Imp_Vh { get; set; }
        public String U_Fin_Prop { get; set; }
        public Int32? U_DiaPago { get; set; }
        public Double? U_Int_Mor { get; set; }
        public String U_Tipo_Cuo { get; set; }
        public String U_Prestamo { get; set; }
        public String U_NC_Prima { get; set; }
        public DateTime? U_SCGD_FDr { get; set; }
        public String U_GenFaAcc { get; set; }
        public String U_Det_Acc { get; set; }
        public String U_Fact_Acc { get; set; }
        public Double? U_Por_Desc { get; set; }
        public Double? U_Por_Temp { get; set; }
        public Double? U_Acc_Desc { get; set; }
        public Double? U_Acc_Imp { get; set; }
        public Double? U_AcDescPo { get; set; }
        public Double? U_AcSinDes { get; set; }
        public Double? U_Acc_Temp { get; set; }
        public Double? U_GL_Temp { get; set; }
        public Double? U_OG_Temp { get; set; }
        public String U_Fact_GA { get; set; }
        public String U_TranU { get; set; }
        public String U_ModU { get; set; }
        public String U_ComU { get; set; }
        public String U_As_FExt { get; set; }
        public Double? U_TotalAcc { get; set; }
        public String U_Sucu { get; set; }
        public String U_CSucu { get; set; }
        public Double? U_Tot_Tram { get; set; }
        public String U_As_Tram { get; set; }
        public String U_TFin { get; set; }
        public String U_FinE { get; set; }
        public Double? U_MontoC { get; set; }
        public String U_CodClasifUs { get; set; }
        public Double? U_ValVeh_Us { get; set; }
        public Double? U_BonoDV { get; set; }
        public Double? U_BonoVV { get; set; }
        public Double? U_BonoDV2 { get; set; }
        public Double? U_DescUni { get; set; }
        public Double? U_PreNet { get; set; }
        public String U_TipIn { get; set; }
        public String U_ColIn { get; set; }
        public String U_Obser { get; set; }
        public String U_PorDes { get; set; }
        public Double? U_AntImp { get; set; }
        public Double? U_MonCBo { get; set; }
        public Double? U_PreLis { get; set; }
        public String U_AsBon { get; set; }
        public Double? U_MoNAs { get; set; }
        public Double? U_MoNFi { get; set; }
        public String U_AsCom { get; set; }
        public Double? U_OtrCos { get; set; }
        public String U_AsOCos { get; set; }
        public String U_ComAse { get; set; }
        public String U_CorrSe { get; set; }
        public String U_CatVeUs { get; set; }
        public Double? U_KmU { get; set; }
        public Double? U_Km_Venta { get; set; }
        public String U_Cod_ProvUS { get; set; }
        public String U_Nom_ProvUS { get; set; }
        public String U_SCGD_ConEjeBan { get; set; }
        public String U_SCGD_NrOC { get; set; }
        public String U_SCGD_NrOL { get; set; }
        public String U_FacTram { get; set; }
        public String U_AsTraFc { get; set; }
        public String U_NoFPVU { get; set; }
        public String U_AsFPVU { get; set; }
        public DateTime? U_SCGD_FechaOC { get; set; }
        public String U_SCGD_Detalle1 { get; set; }
        public String U_SCGD_Detalle2 { get; set; }
        public Int32? U_TipoCV { get; set; }
        public Double? U_FinanciaE { get; set; }
        public String U_EntFinE { get; set; }
        public Double? U_FinanciaT { get; set; }
        public DateTime? U_FecInViSe { get; set; }
        public String U_CliConCod { get; set; }
        public String U_CliConNom { get; set; }
        public String U_CliConRUT { get; set; }
        public String U_NumPropSe { get; set; }
        public String U_Seg_FPT { get; set; }
        public String U_Seg_FPSF { get; set; }
        public String U_SeFP_PC { get; set; }
        public String U_chk_PC { get; set; }
        public String U_BanChe_PC { get; set; }
        public String U_Se_NumIng { get; set; }
        public Double? U_Val_PC { get; set; }
        public Double? U_Tas_AnuEX { get; set; }
        public Int32? U_PlazoEX { get; set; }
        public DateTime? U_Fec_1AbEX { get; set; }
        public Int32? U_DiaPagoEX { get; set; }
        public Double? U_Int_MorEX { get; set; }
        public String U_Tipo_CuoEX { get; set; }
        public Double U_ImpUsado { get; set; }
        public Double U_TotalCImpuest { get; set; }
        public List<AccesoriosXContrato> AccesoriosXContrato { get; set; }
        public List<BonosXContrato> BonosXContrato { get; set; }
        public List<HistorialContrato> HistorialContrato { get; set; }
        public List<LineasRes> LineasRes { get; set; }
        public List<LineasSum> LineasSum { get; set; }
        public List<OtrosCostosXContrato> OtrosCostosXContrato { get; set; }
        public List<TramitesXContrato> TramitesXContrato { get; set; }
        public List<UsadosXContrato> UsadosXContrato { get; set; }
        public List<VehiculosXContrato> VehiculosXContrato { get; set; }
    }
}
